from typing import TypedDict
from src.agents.planning_agent import generate_plan
from src.agents.implementation_agent import generate_implementation
from src.agents.test_agent import generate_test
from src.tools.sandbox import run_code_in_sandbox
from langgraph.graph import StateGraph, END
from src.tools.github_client import github
import time
from langgraph.checkpoint.memory import MemorySaver
from mcp import Client
from src.mcp_servers.sandbox_server import mcp as sandbox_mcp
from src.mcp_servers.github_server import mcp as github_mcp

class DevAgentState(TypedDict):
    issue_description: str
    owner: str
    repo: str
    branch: str
    plan: dict
    original_code: str
    current_code: str
    current_test: str
    test_result: dict
    iteration_count: int
    max_iterations: int
    status: str
    pr_url: str

async def plan_node(state: DevAgentState) -> dict:
    print("PLANNING...")
    plan = generate_plan(state["issue_description"], repo=state["repo"])
    return {"plan": plan, "status": "planned"}


async def implement_node(state: DevAgentState) -> dict:
    print(f"IMPLEMENTING (attempt {state['iteration_count'] + 1})...")
    
    is_retry = state.get("test_result") and not state["test_result"].get("success", True)
    
    implementation = await generate_implementation(
        state["plan"], owner=state["owner"], repo=state["repo"], branch=state["branch"],
        previous_code=state.get("current_code") if is_retry else None,
        test_code=state.get("current_test") if is_retry else None,
        failure_output=state["test_result"].get("stderr") if is_retry else None
    )
    
    updates = {
        "current_code": implementation["updated_code"],
        "iteration_count": state["iteration_count"] + 1,
        "status": "implemented"
    }
    
    if not state.get("original_code"):
        updates["original_code"] = implementation["original_code"]
    
    return updates


async def test_gen_node(state: DevAgentState) -> dict:
    print("GENERATING TEST...")
    
    if state.get("current_test"):
        print("  (reusing existing test)")
        return {}
    
    test = generate_test(
        original_code=state["original_code"],
        updated_code=state["current_code"],
        issue_description=state["issue_description"]
    )
    return {"current_test": test["test_code"]}

async def run_test_node(state: DevAgentState) -> dict:
    print("RUNNING TEST IN SANDBOX...")
    
    files = {
        "solution.py": state["current_code"],
        "test_solution.py": state["current_test"]
    }
    
    async with Client(sandbox_mcp) as client:
        mcp_result = await client.call_tool(
            "run_code",
            {"files": files, "entry_point": "test_solution.py"}
        )
    
    import json
    result = json.loads(mcp_result.content[0].text)
    
    print(f"  Result: {'PASSED' if result['success'] else 'FAILED'}")
    
    return {"test_result": result, "status": "tested"}

async def create_pr_node(state: DevAgentState) -> dict:
    print("CREATING PULL REQUEST...")
    
    branch_name = f"ai-fix-{int(time.time())}"
    file_path = state["plan"]["files_likely_affected"][0]
    
    async with Client(github_mcp) as client:
        await client.call_tool(
            "create_branch",
            {"owner": state["owner"], "repo": state["repo"],
             "branch_name": branch_name, "from_branch": state["branch"]}
        )
        
        sha_result = await client.call_tool(
            "get_file_sha",
            {"owner": state["owner"], "repo": state["repo"],
             "path": file_path, "branch": branch_name}
        )
        current_sha = sha_result.content[0].text if sha_result.content else None
        
        await client.call_tool(
            "update_file",
            {"owner": state["owner"], "repo": state["repo"], "path": file_path,
             "content": state["current_code"],
             "message": f"AI fix: {state['plan']['issue_summary']}",
             "branch": branch_name, "sha": current_sha}
        )
        
        pr_result = await client.call_tool(
            "create_pull_request",
            {"owner": state["owner"], "repo": state["repo"],
             "title": f"AI Fix: {state['plan']['issue_summary']}",
             "body": f"Automated fix generated by AI Dev Agent.\n\nPlan:\n{state['plan']}\n\nTest verification: PASSED",
             "head_branch": branch_name, "base_branch": state["branch"]}
        )
    
    import json
    pr = json.loads(pr_result.content[0].text)
    
    print(f"  PR created: {pr['url']}")
    
    return {"status": "pr_created", "pr_url": pr["url"]}

def should_continue(state: DevAgentState) -> str:
    """
    Decides what happens after a test run:
      - test passed -> we're done, succeed
      - test failed, but we still have retries left -> loop back and try again
      - test failed, and we've hit max_iterations -> give up, report failure
    """
    if state["test_result"].get("infrastructure_error"):
        print("INFRASTRUCTURE ERROR (Docker unreachable) — not a real test failure. Stopping.")
        return "give_up"
    
    if state["test_result"]["success"]:
        print("TEST PASSED — stopping loop.")
        return "success"
    
    if state["iteration_count"] >= state["max_iterations"]:
        print(f"Max iterations ({state['max_iterations']}) reached — giving up.")
        return "give_up"
    
    print("Test failed — retrying implementation.")
    return "retry"

def build_graph():
    graph = StateGraph(DevAgentState)
    
    graph.add_node("plan", plan_node)
    graph.add_node("implement", implement_node)
    graph.add_node("generate_test", test_gen_node)
    graph.add_node("run_test", run_test_node)
    graph.add_node("create_pr", create_pr_node)   # NEW
    
    graph.set_entry_point("plan")
    
    graph.add_edge("plan", "implement")
    graph.add_edge("implement", "generate_test")
    graph.add_edge("generate_test", "run_test")
    
    graph.add_conditional_edges(
        "run_test",
        should_continue,
        {
            "success": "create_pr",   # CHANGED — was END, now goes to create_pr
            "give_up": END,
            "retry": "implement"
        }
    )
    
    graph.add_edge("create_pr", END)
    
    checkpointer = MemorySaver()
    
    return graph.compile(
        checkpointer=checkpointer,
        interrupt_before=["create_pr"]   # <- pause right before this node runs
    )